ALTER ROLE [db_owner] ADD MEMBER [NT AUTHORITY\SYSTEM];


GO
ALTER ROLE [db_owner] ADD MEMBER [NT SERVICE\SQLWriter];


GO
ALTER ROLE [db_owner] ADD MEMBER [NT SERVICE\Winmgmt];


GO
ALTER ROLE [db_owner] ADD MEMBER [NT AUTHORITY\NETWORK SERVICE];

